import type { Metadata } from "next";
import { Cinzel, Caudex, Montserrat } from 'next/font/google';
import { Navbar } from "@/app/components/ui/Nanvar";
import { Search } from "@/app/components/ui/Search";
import "./globals.css";

const cinzel = Cinzel({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-cinzel',
  display: 'swap',
});

const caudex = Caudex({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-caudex',
  display: 'swap',
});

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-montserrat',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${cinzel.variable} ${caudex.variable} ${montserrat.variable} font-sans dark`}
      >
        <div className="bg-background">
          <Navbar />
          <Search />
        </div>
        {children}
      </body>
    </html>
  );
}
